// <auto-generated />
namespace PizzaShopJan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_MIME : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_MIME));
        
        string IMigrationMetadata.Id
        {
            get { return "201804200803568_Add_MIME"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
